In [2]:
using(LinearAlgebra)

#### Zadanie 1 (1pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

In [3]:
A = rand(1000, 1000)
x_original = rand(1000)

1000-element Array{Float64,1}:
 0.31883684745362517
 0.9608420659174708
 0.16375997561702027
 0.051356745360099376
 0.29781226431479
 0.387801183322273
 0.1441856084784734
 0.7073606317990686
 0.7778078727851931
 0.42379395319056834
 0.6338372262721446
 0.8950225792446003
 0.5575611657836208
 ⋮
 0.8948534704183522
 0.7375165156314585
 0.14150303031868772
 0.5675154855734954
 0.5355601658567763
 0.4032405072259415
 0.33799970024755743
 0.6981598260123805
 0.3847619002109637
 0.37028816604045534
 0.002812643590498043
 0.9251604427504128

In [4]:
b = A * x_original

1000-element Array{Float64,1}:
 244.34987472141026
 252.7654196392798
 256.3681003033508
 252.12681668698227
 251.5797275244023
 244.45494398826602
 248.12997127627955
 248.11017771428243
 247.0788458714232
 244.03482248588324
 250.6183462622642
 243.28382209921946
 242.77414662069228
   ⋮
 241.91721544044566
 251.03578599558796
 234.1266732906108
 242.67866964470775
 251.4563508452119
 240.2215742749175
 252.60471038365705
 247.6805373219931
 254.2431321130997
 242.99737038959128
 243.34448183292469
 246.53618363324878

In [5]:
# nieefektywny przyklad
x_inv = inv(A) * b

1000-element Array{Float64,1}:
 0.3188368474531025
 0.9608420659192802
 0.163759975614866
 0.05135674535877399
 0.29781226431424557
 0.38780118332406666
 0.1441856084781996
 0.7073606317985934
 0.7778078727847024
 0.42379395319031943
 0.6338372262710479
 0.8950225792444826
 0.5575611657834223
 ⋮
 0.8948534704190649
 0.7375165156290961
 0.14150303031385647
 0.5675154855733275
 0.5355601658585627
 0.40324050722576743
 0.33799970024757897
 0.6981598260126578
 0.38476190021049206
 0.3702881660386197
 0.0028126435900990288
 0.9251604427559812

In [6]:
# z uzyciem zoptymalizowanego operatora "\"
x_slash = A \ b

1000-element Array{Float64,1}:
 0.31883684745257435
 0.9608420659178042
 0.16375997561672814
 0.051356745360656805
 0.2978122643145239
 0.3878011833223188
 0.14418560847866826
 0.7073606317999145
 0.7778078727849957
 0.4237939531906843
 0.6338372262710954
 0.895022579244341
 0.5575611657837309
 ⋮
 0.8948534704183403
 0.7375165156301247
 0.14150303031921163
 0.5675154855737945
 0.5355601658578863
 0.4032405072259701
 0.3379997002480392
 0.6981598260127209
 0.38476190021028295
 0.3702881660395127
 0.0028126435904065827
 0.9251604427519841

In [7]:
# faktoryzacja LU
A = factorize(A)
x_lu = A \ b

1000-element Array{Float64,1}:
 0.31883684745257435
 0.9608420659178042
 0.16375997561672814
 0.051356745360656805
 0.2978122643145239
 0.3878011833223188
 0.14418560847866826
 0.7073606317999145
 0.7778078727849957
 0.4237939531906843
 0.6338372262710954
 0.895022579244341
 0.5575611657837309
 ⋮
 0.8948534704183403
 0.7375165156301247
 0.14150303031921163
 0.5675154855737945
 0.5355601658578863
 0.4032405072259701
 0.3379997002480392
 0.6981598260127209
 0.38476190021028295
 0.3702881660395127
 0.0028126435904065827
 0.9251604427519841

In [8]:
function get_quality(x)
    diff = x - x_original
    return sqrt(dot(diff, diff))
end

get_quality (generic function with 1 method)

In [9]:
# initializing
A = rand(1000, 1000)
x_original = rand(1000)
b = A * x_original

# first compilation
inv(A) * b
A \ b
Af = factorize(A)
Af \ b

iters = 10
t_inv = 0
t_slash = 0
t_lu = 0

for t in 1:iters
    t_inv += @elapsed x_inv = inv(A) * b
    t_slash += @elapsed x_slash = A \ b
    t_lu += @elapsed Af = factorize(A); x_lu = Af \ b
end

# average time
t_inv /= iters
t_slash /= iters
t_lu /= iters
println("inv()     time: ", t_inv)
println("\\         time: ", t_slash)
println("factorize time: ", t_lu)

println("-----------------------------------------")

q_inv = get_quality(x_inv)
q_slash = get_quality(x_slash)
q_lu = get_quality(x_lu)
println("inv()     quality: ", q_inv)
println("\\         quality: ", q_slash)
println("factorize quality: ", q_lu)


inv()     time: 0.036499670000000005
\         time: 0.022906569999999998
factorize time: 0.014048229999999998
-----------------------------------------
inv()     quality: 3.915693796605548e-11
\         quality: 2.990167592860418e-11
factorize quality: 2.990167592860418e-11


#### Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.



In [10]:
using CSV
using DataFrames
using Statistics

In [11]:
time_df = CSV.read("multiplying_time.csv", DataFrame)
# getting matrix vector multiplication results
mv_frame =  filter(row -> row.TYPE in ["MV"], time_df)
mv_size_grouped = groupby(mv_frame, :SIZE)
mv_avrg = combine(mv_size_grouped, :TIME => mean => :mean_time)

10×2 DataFrame
 Row │ SIZE   mean_time  
     │ Int64  Float64    
─────┼───────────────────
   1 │   500  0.00452073
   2 │  1000  0.0131747
   3 │  1500  0.0285138
   4 │  2000  0.063156
   5 │  2500  0.140981
   6 │  3000  0.255901
   7 │  3500  0.357966
   8 │  4000  0.531104
   9 │  4500  0.640824
  10 │  5000  0.798477

In [13]:
using Polynomials
x = mv_avrg[!, :SIZE]
y = mv_avrg[!, :mean_time]

Polynomial(0.008035857166666608 - 4.384724595454542e-5*x + 4.114347378787879e-8*x^2)

In [17]:
A = zeros(length(x), 3)
A[:,1] = x.^2
A[:,2] = x
A[:,3] = ones(length(x))

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [20]:
res = A \ y

3-element Array{Float64,1}:
  4.1143473787878716e-8
 -4.384724595454507e-5
  0.008035857166666141

In [21]:
fit(x, y, 2)

Polynomial(0.008035857166666608 - 4.384724595454542e-5*x + 4.114347378787879e-8*x^2)

Jak widzimy współczynniki wyliczone wprost tworząc układ równań są niemal identyczne z wynikami otrzymanymi za pomocą funkcji fit()